# battery power report interval [s]
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# keyboard debounce [ms] aka ghosting 
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Increase the transmission power of the keyboard's BLE radio 
# to solve the problem of delay and poor left-right communication
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Change the keyboard's default display name
CONFIG_ZMK_KEYBOARD_NAME="Sofle_RGB"
# Used to fix errors related to battery reporting in Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# OLED settings
# Enable display
CONFIG_ZMK_DISPLAY=y
# Disable the default status screen to show Bongo Cat
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
# Keep the screen on to see the animation
CONFIG_ZMK_DISPLAY_SCREEN_BLANKING_OFF=y
# Enable Bongo Cat Widget
CONFIG_ZMK_WIDGET_BONGO_CAT_STATUS=y

#Hibernation settings
# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# zmk studio settings
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB settings
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
# Turn off RGB when the keyboard enters idle state
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60

# Knob settings
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Split keyboard settings
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y